"""Add basic tables

Revision ID: 96c8cb833a51
Revises: aadb6c0a6959
Create Date: 2025-04-03 15:27:25.322298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c8cb833a51'
down_revision: Union[str, None] = 'aadb6c0a6959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redeemr_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('points_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redeemr_rewards_id'), 'redeemr_rewards', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reward_id'], ['redeemr_rewards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_index('ix_loyalty_items_id', table_name='loyalty_items')
    op.drop_table('loyalty_items')
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=True)
    op.drop_constraint('businesses_owner_id_fkey', 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'owner_id')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'name')
    op.add_column('businesses', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('businesses_owner_id_fkey', 'businesses', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.create_table('loyalty_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('points_required', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='loyalty_items_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='loyalty_items_pkey')
    )
    op.create_index('ix_loyalty_items_id', 'loyalty_items', ['id'], unique=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_redeemr_rewards_id'), table_name='redeemr_rewards')
    op.drop_table('redeemr_rewards')
    # ### end Alembic commands ###
